spring:
    application:
        name: oauth2-login-demo
    security:
        oauth2:
            client:
                registration:
                    github:
                        client-id: Ov23li05vdO5DvDJalx9
                        client-secret: 3b70a29c1c93f6775688c2f4f1bf03dbacb6117f